config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root "posts#index"

  %w(manage about).each do |page|
    get "pages/#{page}", path: "/#{page}"
  end

  get '/posts/heart/:id', to: 'posts#upvote', as: 'post_upvote', path: 'posts/:id/heart'
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :text

  acts_as_votable

  include NextPrev
  include Presentation
end

app/models/post/next_prev.rb
module Post::NextPrev
  def next
    Post.where("id > ?", id).first
  end

  def prev
    Post.where("id < ?", id).last
  end
end

app/models/post/presentation.rb
module Post::Presentation
  def pretty_created_at
    created_at.to_time.strftime('%B %e at %l:%M %p')
  end


  def heart_count
    "#{self.get_upvotes.count} #{singular_or_plural}"
  end

  private

  def singular_or_plural
    self.get_upvotes.count == 1 ? 'heart' : 'hearts'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def confirm_logged_in
    unless current_user
      flash[:notice] = "Please log in"
      redirect_to root_path
      return false
    else
      return true
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def manage
    @posts = Post.all.reverse
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :confirm_logged_in, only: [:edit, :update, :destroy, :create, :upvote]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.reverse
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
      @post.vote_by voter: current_user
      redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "My Blog", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Manage", pages_manage_path %></li>
        <li><%= link_to "About", pages_about_path %></li>
        <% if signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
          
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloggr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/navbar" %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.  This is the about page.

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/manage.html.erb
<h1>Listing Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.text %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :text %><br>
    <%= f.text_area :text, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="post-index">
  <% @posts.each do |post| %>
    <h1><%= link_to post.title, post %></h1>


    <%= link_to post_upvote_path(post) do %>
      <i class="glyphicon glyphicon-heart btn btn-danger pull-right heart-button"></i>
    <% end %>


    <p><%= post.text %></p>
    <p><i>Posted on <%= post.pretty_created_at %></i></p>

    <p class='pull-right'><small><%= post.heart_count %></small></p>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @post.title %></h1>

<%= link_to post_upvote_path(@post) do %>
  <i class="glyphicon glyphicon-heart btn btn-danger heart-button"></i>
<% end %>

<p><small><%= @post.heart_count %></small></p>

<br />

<div>
  <%= @post.text %>
</div>


<br />
<br />

<p>
<%= link_to "<< prev", @post.prev %>
<%= link_to "next >>", @post.next %>
</p>